server {
    listen 80;
    
    # Directorio donde están los archivos compilados
    root /usr/share/nginx/html;
    index index.html;

    # Compresión gzip para que la app cargue más rápido
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Intenta servir el archivo solicitado ($uri), si no existe, sirve index.html
        # Esto permite que el Router de React maneje las rutas
        try_files $uri $uri/ /index.html;
    }

    # Caché para archivos estáticos (js, css, imágenes) por 1 año
    location ~* \.(?:css|js|jpg|svg|png|gif|ico)$ {
        expires 1y;
        add_header Cache-Control "public";
    }
}